name: 'uri-checker-compose'

services:
  redis:
    image: redis
    env_file:
      - .env
    ports:
      - ${COMPOSE__REDIS__HOST}:${COMPOSE__REDIS__PORT}:6379
    volumes:
      - redis-data:/data
  rabbitmq:
    image: rabbitmq:3.8.27-management-alpine
    ports:
      - ${COMPOSE__RABBITMQ__HOST}:${COMPOSE__RABBITMQ__PORT}:5672
      - ${COMPOSE__RABBITMQ__HOST}:${COMPOSE__RABBITMQ__PORT_2}:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  web:
    restart: unless-stopped
    image: 127.0.0.1:5000/uri-checker-web
    build:
      context: .
    env_file:
      - .env
    ports:
      - ${COMPOSE__WEB__HOST}:${COMPOSE__WEB__PORT}:8000
    command: python main.py
    depends_on:
      - rabbitmq
      - redis
  taskiq-worker:
    restart: unless-stopped
    profiles:
      - dev
    image: 127.0.0.1:5000/uri-checker-taskiq-worker
    build:
      context: .
    env_file:
      - .env
    command: taskiq worker main:broker
    depends_on:
      - rabbitmq
      - redis
    deploy:
      mode: replicated
      replicas: 2
volumes:
  redis-data:
  rabbitmq-data:
