name: 'uri-discover'

services:
  redis:
    image: redis
    env_file:
      - .env
    ports:
      - ${REDIS_HOST}:${REDIS_PORT}:6379
    volumes:
      - redis-data:/data
  rabbitmq:
    image: rabbitmq:3.8.27-management-alpine
    env_file:
      - .env
    ports:
      - ${RABBITMQ_HOST}:${RABBITMQ_PORT}:5672
      - ${RABBITMQ_HOST}:${RABBITMQ_PORT_2}:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  web:
    restart: unless-stopped
    image: 127.0.0.1:5000/uri-discover-web
    build:
      context: .
    env_file:
      - .env
    ports:
      - ${WEB_HOST}:${WEB_PORT}:8000
    command: python main.py
    depends_on:
      - rabbitmq
      - redis
  taskiq-worker:
    restart: unless-stopped
    image: 127.0.0.1:500/uri-discover-taskiq-worker
    build:
      context: .
    env_file:
      - .env
    command: taskiq worker main:broker
    depends_on:
      - rabbitmq
      - redis
    deploy:
      mode: replicated
      replicas: 2
  registry:
    image: registry
    ports:
      - 127.0.0.1:5000:5000
volumes:
  redis-data:
  rabbitmq-data:
