services:
  taskiq-worker:
    image: 127.0.0.1:5000/uri-discover-taskiq-worker
    command: taskiq worker main:broker
    deploy:
      replicas: 2
  registry:
    image: registry
    ports:
      - 127.0.0.1:5000:5000
